# Generated by Django 3.1.7 on 2022-10-27 03:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('lightweight', 'Lightweight'), ('middleweight', 'Middleweight'), ('cruiserweight', 'Cruiserweight'), ('heavyweight', 'Heavyweight')], max_length=15)),
                ('weight_limit', models.FloatField(validators=[django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('idle', 'IDLE'), ('loading', 'LOADING'), ('loaded', 'LOADED'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('returning', 'RETURNING')], default='idle', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z0-9_-]', message='Only latters, number, underscore and dash')])),
                ('weight', models.FloatField(validators=[django.core.validators.MaxValueValidator(500)])),
                ('code', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', message='Only upper case latters , number and underscore')])),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drone')),
                ('medication', models.ManyToManyField(to='core.Medication')),
            ],
        ),
    ]
