# Generated by Django 3.1.7 on 2022-10-29 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221027_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='battery_capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight_limit',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='weight in gr'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]', message='Only latters, number, underscore and dash')]),
        ),
    ]
